import '@radix-ui/themes/styles.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NavBar from './NavBar'
import './globals.css'
import './theme-config.css'

import { Theme } from '@radix-ui/themes'
import AuthProvider from './auth/Provider'


const inter = Inter({ 
  subsets: ['latin'] ,
  variable: '--font-inter',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <AuthProvider> {/* To use useSession hook */}
      <Theme appearance="light" accentColor="violet">
        <NavBar/>
        <main className='p-2'>
          {children}
          </main>
        </Theme>
        </AuthProvider>
        </body>
    </html>
  )
}
